name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies with legacy peer deps
      - run: cd src && npm install --legacy-peer-deps

      # Lint the project
      - run: cd src && npm run lint